baseURL = "https://theastrowolfe.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "The Astro Wolfe"
theme = "cupper"
googleAnalytics = ""
disqusShortname = ""
enableGitInfo = false

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "[@theastrowolfe](https://twitter.com/theastrowolfe)"
  homeMetaContent = "Joshua Wolfe"
  footer = "Made with [Hugo](https://gohugo.io/)"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 1, 1970"
  codePenUser = "theastrowolfe"
  katex = true

[menu]
  [[menu.nav]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
#  [[menu.nav]]
#    name = "Showcase"
#    url = "/showcase/"
#    weight = 3
#  [[menu.nav]]
#    name = "Tutorials"
#    url = "/tutorials/"
#    weight = 4
